name: On deploy

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true


jobs:
  print-tag:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Print the input tag to STDOUT
        run: echo  The tag is ${{ github.event.inputs.tag }}
      - name: Print the input tags to STDOUT
        run: echo  The tag is ${{ github.event.inputs.tags }}
      - name: Print the input environment to STDOUT
        run: echo  The environment is ${{ github.event.inputs.environment }}
      - name: Print the input logLevel to STDOUT
        run: echo  The logLevel is ${{ github.event.inputs.logLevel }}
      - name: Print the input secret to STDOUT
        run: echo  The secret is ${{ secrets.PROFILE_NAME }}